In [2]:
"""Neden NumPy Kullanmalı?
-Python listelerinden daha hızlı ve verimlidir
- Diziler üzerinde eleman bazında işlemler yapmayı sağlar
- Bilimsel hesaplama ve veri analizi için gereklidir"""

#NumPy'de Dizi Oluşturma
import numpy as np
dizi = np.array([1,2,3])
print(dizi)

[1 2 3]


In [3]:
#NumPy Veri Tipleri
import numpy as np
dizi = np.array([1,2,3], dtype='float32')
print(dizi)


[1. 2. 3.]


In [4]:
#Dizi İndeksleme ve Dilimleme
import numpy as np
dizi = np.array([10,20,30,40])
ilk_eleman = dizi[0]
dilim = dizi[1:3]
print(ilk_eleman)
print(dilim)

10
[20 30]


In [5]:
#Dizi İşlemleri
import numpy as np
dizi1 = np.array([1,2,3])
dizi2 = np.array([4,5,6])
sonuc = dizi1+dizi2
print(sonuc)

[5 7 9]


In [6]:
#Verileri Özetleme
import numpy as np
dizi = np.array([1,2,3,4,5,6])
ortalama = np.mean(dizi)
toplam = np.sum(dizi)
print(ortalama)
print(toplam)

3.5
21


In [7]:
#Gelişmiş İndeksleme
import numpy as np
dizi = np.array([1,2,3,4,5,6,7,8,9,0])
kosullu_dizi = dizi[dizi>5]
print(kosullu_dizi)

[6 7 8 9]


In [8]:
#N Boyutlu Diziler
import numpy as np
dizi = np.ones((3,3,3))
print(dizi)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
#NumPy'deki Matematiksel Fonksiyonlar
import numpy as np
dizi = np.array([1,4,9,0])
karekok = np.sqrt(dizi)
print(karekok)

[1. 2. 3. 0.]


In [10]:
#NumPy'de Doğrusal Cebir
"""-Matris çarpımı: `np.dot()`
   - Matris tersini alma: `np.linalg.inv()`"""
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
sonuc = np.dot(A, B)
print(sonuc)

[[19 22]
 [43 50]]


In [11]:
#NumPy'de Doğrusal Cebir
#- Matris çarpımı: `np.dot()`
#- Matris tersini alma: `np.linalg.inv()`


In [12]:
#NumPy'de Yayınlama (Broadcasting)
import numpy as np
dizi = np.array([1,2,3])
sonuc = dizi+5
print(sonuc)


[6 7 8]
